services:
  - type: web
    name: honus-autos
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /cardealership/login/login.php
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: cardealership
