<?php
require_once __DIR__ . '/../includes/auth.php';require_once __DIR__ . '/../includes/layout.php';require_once __DIR__ . '/../includes/cars.php';require_once __DIR__ . '/../../form/inc/connect.php';require_admin();
$id=(int)($_GET['order_id']??$_POST['order_id']??0);$saved=false;
if($_SERVER['REQUEST_METHOD']==='POST'&&$id>0){$payment=trim($_POST['payment_status']??'Pending');$status=trim($_POST['order_status']??'Processing');$allowedP=['Pending','Paid'];$allowedS=['Processing','Preparing Vehicle','Ready for Pickup','Completed','Cancelled'];if(in_array($payment,$allowedP,true)&&in_array($status,$allowedS,true)){ $st=$con->prepare('UPDATE orders SET payment_status=?,order_status=? WHERE id=?');if($st){$st->bind_param('ssi',$payment,$status,$id);$st->execute();$st->close();$saved=true;}}}
$order=null;if($con&&$con!==false&&$id>0){$st=$con->prepare('SELECT o.*,u.username,u.email,c.name car_name,c.price car_price,c.images car_images FROM orders o JOIN user_data u ON u.id=o.user_id LEFT JOIN cars c ON c.id=o.car_id WHERE o.id=? LIMIT 1');if($st){$st->bind_param('i',$id);$st->execute();$order=$st->get_result()->fetch_assoc();$st->close();}}
render_page_start('Confirm Payment | Admin');render_navbar('Admin');
echo '<div class="page">';
if(!$order){echo '<div class="card"><h2>Order not found</h2><a class="btn-secondary" href="dashboard.php" style="margin-top:16px">Back to Dashboard</a></div>';}else{ $images=[];if(!empty($order['car_images'])){$images=json_decode($order['car_images'],true);if(!is_array($images))$images=[$order['car_images']];}$img=!empty($images[0])?$images[0]:'images/placeholder.svg'; echo '<div class="card" style="max-width:1000px;margin:0 auto"><div style="display:flex;justify-content:space-between;align-items:flex-start;gap:20px;flex-wrap:wrap"><div><h2>Confirm Payment</h2><p class="muted">Review the order before changing its payment and delivery status.</p></div><span class="pill">Order #'.(int)$order['id'].'</span></div>';if($saved)echo '<p class="success" style="margin-top:16px">Order status updated successfully.</p>';echo '<div class="grid grid-2" style="margin-top:24px"><div><img src="'.esc(car_image_url($img)).'" style="width:100%;height:300px;object-fit:cover;border-radius:20px" alt=""></div><div><h3>'.esc($order['car_name']??'Vehicle removed').'</h3><p class="muted" style="margin-top:4px">Customer: '.esc($order['username']).' · '.esc($order['email']).'</p><p style="margin-top:18px;font-size:1.4rem"><strong>$'.number_format((float)$order['amount'],2).'</strong></p><div style="margin-top:18px;padding:16px;border:1px solid var(--border);border-radius:16px;background:var(--surface-alt)"><strong>Payment method</strong><p class="muted">'.esc($order['payment_method']).'</p></div></div></div>';echo '<form method="post" style="margin-top:24px"><input type="hidden" name="order_id" value="'.(int)$order['id'].'"><div class="grid grid-2"><div><label>Payment Status</label><select name="payment_status"><option value="Pending"'.($order['payment_status']==='Pending'?' selected':'').'>Pending</option><option value="Paid"'.($order['payment_status']==='Paid'?' selected':'').'>Paid</option></select></div><div><label>Order Status</label><select name="order_status">';foreach(['Processing','Preparing Vehicle','Ready for Pickup','Completed','Cancelled'] as $v)echo '<option value="'.esc($v).'"'.($order['order_status']===$v?' selected':'').'>'.esc($v).'</option>';echo '</select></div></div><div class="actions" style="margin-top:18px"><button class="btn-primary" type="submit">Save Confirmation</button><a class="btn-secondary" href="dashboard.php">Back to Orders</a></div></form></div>';}
echo '</div>';render_page_end();
