<?php
return [
    [
        'id' => 1,
        'name' => 'BMW M4 Competition',
        'tagline' => 'A precision-engineered sports coupe with championship pace.',
        'year' => '2025',
        'price' => '$65,000',
        'mileage' => '8,200 miles',
        'exterior_color' => 'Alpine White',
        'interior_color' => 'Black Leather',
        'status' => 'In Stock',
        'engine' => '3.0L Twin-Turbo I6',
        'horsepower' => '510 hp',
        'torque' => '479 lb-ft',
        'transmission' => '8-Speed Automatic',
        'drivetrain' => 'RWD',
        'top_speed' => '189 mph',
        'zero_to_sixty' => '3.8 sec',
        'features' => [
            'Carbon Fiber Package',
            'Adaptive Suspension',
            'Premium Harman Kardon Audio',
            'Heated and Ventilated Seats',
        ],
        'description' => "The BMW M4 Competition is crafted for drivers who demand both ruthless performance and everyday luxury. Its high-revving twin-turbo engine delivers storming acceleration, while the finely tuned chassis offers precise control for canyon runs and highways alike.",
        'description_long' => "Inside the cabin, premium materials and driver-focused ergonomics set a commanding tone. The advanced infotainment system and performance telemetry ensure every drive feels intelligent and connected.",
        'images' => [
            'images/bmw-m4-competition.webp',
        ],
    ],
    [
        'id' => 2,
        'name' => 'Mercedes-Benz C63 AMG',
        'tagline' => 'Luxury coupe engineering fused with raw AMG power.',
        'year' => '2025',
        'price' => '$83,000',
        'mileage' => '5,400 miles',
        'exterior_color' => 'Obsidian Black',
        'interior_color' => 'Red/Black Nappa',
        'status' => 'In Stock',
        'engine' => '4.0L Twin-Turbo V8',
        'horsepower' => '503 hp',
        'torque' => '516 lb-ft',
        'transmission' => '9-Speed Automatic',
        'drivetrain' => 'RWD',
        'top_speed' => '180 mph',
        'zero_to_sixty' => '3.9 sec',
        'features' => [
            'AMG Performance Exhaust',
            'Nappa Leather Seats',
            'Apple CarPlay / Android Auto',
            'Multicontour Front Seats',
        ],
        'description' => "The C63 AMG combines upscale materials with an intoxicating V8 soundtrack. Its athletic design and aggressive stance are backed by precision engineering from Mercedes-AMG.",
        'description_long' => "This coupe delivers a confidence-inspiring drive whether navigating city streets or accelerating down the freeway. The intuitive cabin and premium tech reinforce its luxury performance identity.",
        'images' => [
            'images/mercedes-c63-amg.jpg',
        ],
    ],
    [
        'id' => 3,
        'name' => 'Audi RS7',
        'tagline' => 'Sleek, powerful, and refined for modern grand touring.',
        'year' => '2025',
        'price' => '$91,000',
        'mileage' => '6,100 miles',
        'exterior_color' => 'Matte Gray',
        'interior_color' => 'Ivory Leather',
        'status' => 'In Stock',
        'engine' => '4.0L Twin-Turbo V8',
        'horsepower' => '591 hp',
        'torque' => '590 lb-ft',
        'transmission' => '8-Speed Automatic',
        'drivetrain' => 'AWD',
        'top_speed' => '190 mph',
        'zero_to_sixty' => '3.5 sec',
        'features' => [
            'Bang & Olufsen Premium Sound',
            'Quattro AWD',
            'Digital Cockpit',
            'Sport Differential',
        ],
        'description' => "The Audi RS7 offers immediate power delivery and sumptuous cabin refinement. Its athletic silhouette hides one of the most sophisticated performance sedans on the road.",
        'description_long' => "Advanced driver assists and adaptive cruise control make long journeys effortless, while its track-capable setup ensures performance remains the centerpiece.",
        'images' => [
            'images/audi-rs7.jpg',
        ],
    ],
    [
        'id' => 4,
        'name' => 'Porsche 911 Turbo',
        'tagline' => 'Timeless performance with surgical precision and luxury.',
        'year' => '2025',
        'price' => '$120,000',
        'mileage' => '3,900 miles',
        'exterior_color' => 'Jet Black',
        'interior_color' => 'Graphite',
        'status' => 'In Stock',
        'engine' => '3.8L Twin-Turbo Flat-6',
        'horsepower' => '572 hp',
        'torque' => '553 lb-ft',
        'transmission' => '8-Speed PDK',
        'drivetrain' => 'AWD',
        'top_speed' => '198 mph',
        'zero_to_sixty' => '2.7 sec',
        'features' => [
            'Adaptive Aerodynamics',
            'Porsche Active Suspension',
            'Premium Leather Interior',
            'Sport Chrono Package',
        ],
        'description' => "The 911 Turbo marries Porsche heritage with blistering speed. Its trustworthy handling and luxury fit-and-finish make it a performance icon.",
        'description_long' => "With precise steering and immediate throttle response, this car feels both responsive and composed. Its cabin blends premium comfort with intuitive controls.",
        'images' => [
            'images/porsche-911-turbo.jpg',
        ],
    ],
    [
        'id' => 5,
        'name' => 'Lamborghini Huracán',
        'tagline' => 'A raging supercar with dramatic style and unrivaled excitement.',
        'year' => '2024',
        'price' => '$250,000',
        'mileage' => '4,200 miles',
        'exterior_color' => 'Arancio Borealis',
        'interior_color' => 'Black Leather',
        'status' => 'In Stock',
        'engine' => '5.2L V10',
        'horsepower' => '631 hp',
        'torque' => '417 lb-ft',
        'transmission' => '7-Speed Dual-Clutch',
        'drivetrain' => 'AWD',
        'top_speed' => '202 mph',
        'zero_to_sixty' => '2.9 sec',
        'features' => [
            'Launch Control',
            'Sport Exhaust System',
            'Carbon Fiber Interior',
            'Lamborghini Infotainment System',
        ],
        'description' => "The Huracán is engineered to excite at every turn. Its V10 engine and angular design command attention and deliver a visceral driving experience.",
        'description_long' => "From its lightweight chassis to its dynamic handling, this supercar is built for drivers who value thrilling performance and bold style.",
        'images' => [
            'images/lamborghini-huracan.jpg',
        ],
    ],
    [
        'id' => 6,
        'name' => 'Ferrari F8 Tributo',
        'tagline' => 'Ferrari artistry fused with brutal speed and precision control.',
        'year' => '2024',
        'price' => '$280,000',
        'mileage' => '2,800 miles',
        'exterior_color' => 'Rosso Corsa',
        'interior_color' => 'Black/Red',
        'status' => 'In Stock',
        'engine' => '3.9L Twin-Turbo V8',
        'horsepower' => '710 hp',
        'torque' => '568 lb-ft',
        'transmission' => '7-Speed Dual-Clutch',
        'drivetrain' => 'RWD',
        'top_speed' => '211 mph',
        'zero_to_sixty' => '2.9 sec',
        'features' => [
            'Ferrari Drive Mode Selector',
            'Premium Italian Leather',
            'Adaptive Suspension',
            'Advanced Aerodynamics Package',
        ],
        'description' => "This Ferrari F8 Tributo embodies exotic Italian design and race-derived power. Its focused driving dynamics deliver an unforgettable sensory experience.",
        'description_long' => "Precise chassis balance and edge-of-your-seat acceleration make the F8 a supercar masterpiece. The lavish interior ensures every journey feels dramatic and bespoke.",
        'images' => [
            'images/ferrari-f8-tributo.jpg',
        ],
    ],
    [
        'id' => 7,
        'name' => 'Lexus LX 600',
        'tagline' => 'Executive SUV comfort combined with robust luxury performance.',
        'year' => '2025',
        'price' => '$105,000',
        'mileage' => '7,100 miles',
        'exterior_color' => 'Graphite Black',
        'interior_color' => 'Beige Semi-Aniline',
        'status' => 'In Stock',
        'engine' => '3.5L Twin-Turbo V6',
        'horsepower' => '409 hp',
        'torque' => '479 lb-ft',
        'transmission' => '10-Speed Automatic',
        'drivetrain' => 'AWD',
        'top_speed' => '143 mph',
        'zero_to_sixty' => '6.1 sec',
        'features' => [
            'Executive Seating',
            'Mark Levinson Audio',
            'Panoramic View Monitor',
            'Rear Seat Entertainment',
        ],
        'description' => "The LX 600 blends premium SUV capability with serene interior luxury. Its commanding presence is matched by a composed and quiet ride.",
        'description_long' => "Large, luxurious seating and advanced amenities make this SUV ideal for both family travel and executive transport.",
        'images' => [
            'images/lexus-lx-600.jpg',
        ],
    ],
    [
        'id' => 8,
        'name' => 'Range Rover SVR',
        'tagline' => 'A commanding high-performance SUV with opulent refinement.',
        'year' => '2025',
        'price' => '$115,000',
        'mileage' => '6,500 miles',
        'exterior_color' => 'Santorini Black',
        'interior_color' => 'Ebony Leather',
        'status' => 'In Stock',
        'engine' => '5.0L Supercharged V8',
        'horsepower' => '575 hp',
        'torque' => '516 lb-ft',
        'transmission' => '8-Speed Automatic',
        'drivetrain' => 'AWD',
        'top_speed' => '176 mph',
        'zero_to_sixty' => '4.3 sec',
        'features' => [
            'Terrain Response 2',
            'Carbon Fiber Interior Trim',
            'Meridian Sound System',
            'Adaptive Dynamics',
        ],
        'description' => "The Range Rover SVR is engineered for luxury drivers who demand effortless power and elegant style. Its performance credentials are backed by robust off-road capability.",
        'description_long' => "This SUV delivers refined comfort and commanding road presence, making it ideal for grand touring and weekend escapes.",
        'images' => [
            'images/range-rover-svr.jpg',
        ],
    ],
    [
        'id' => 9,
        'name' => 'Rolls-Royce Ghost',
        'tagline' => 'The pinnacle of ultra-luxury motoring with graceful composure.',
        'year' => '2024',
        'price' => '$300,000',
        'mileage' => '2,200 miles',
        'exterior_color' => 'Cashmere',
        'interior_color' => 'Sable and Ivory',
        'status' => 'In Stock',
        'engine' => '6.75L Twin-Turbo V12',
        'horsepower' => '563 hp',
        'torque' => '627 lb-ft',
        'transmission' => '8-Speed Automatic',
        'drivetrain' => 'RWD',
        'top_speed' => '155 mph',
        'zero_to_sixty' => '4.8 sec',
        'features' => [
            'Starlight Headliner',
            'Executive Rear Seating',
            'Bespoke Interior Trim',
            'Night Vision Assist',
        ],
        'description' => "The Ghost is a statement of craftsmanship, offering serene power and supreme comfort. Every surface is meticulously finished for the ultimate luxury experience.",
        'description_long' => "Its whisper-quiet cabin and effortless acceleration create a sanctuary on wheels, allowing occupants to arrive refreshed and inspired.",
        'images' => [
            'images/rolls-royce-ghost.jpg',
        ],
    ],
    [
        'id' => 10,
        'name' => 'McLaren 720S',
        'tagline' => 'A dramatic supercar built for pure performance and presence.',
        'year' => '2024',
        'price' => '$315,000',
        'mileage' => '1,900 miles',
        'exterior_color' => 'Papaya Orange',
        'interior_color' => 'Black Alcantara',
        'status' => 'In Stock',
        'engine' => '4.0L Twin-Turbo V8',
        'horsepower' => '720 hp',
        'torque' => '568 lb-ft',
        'transmission' => '7-Speed Dual-Clutch',
        'drivetrain' => 'RWD',
        'top_speed' => '212 mph',
        'zero_to_sixty' => '2.8 sec',
        'features' => [
            'Carbon Ceramic Brakes',
            'Active Aerodynamics',
            'Performance Instrument Cluster',
            'Premium Audio System',
        ],
        'description' => "The McLaren 720S is a track-focused machine with a sculpted body and relentless acceleration. It blends exotic styling with race-bred engineering.",
        'description_long' => "Every detail is tuned for speed, confidence, and a thrilling connection to the road. It is a true modern supercar icon.",
        'images' => [
            'images/McLaren%20720S.jpg',
        ],
    ],
    [
        'id' => 11,
        'name' => 'Bentley Continental GT',
        'tagline' => 'Grand touring elegance with effortless power and prestige.',
        'year' => '2025',
        'price' => '$205,000',
        'mileage' => '4,600 miles',
        'exterior_color' => 'Moonbeam',
        'interior_color' => 'Camel Tan',
        'status' => 'In Stock',
        'engine' => '4.0L Twin-Turbo V8',
        'horsepower' => '542 hp',
        'torque' => '568 lb-ft',
        'transmission' => '8-Speed Automatic',
        'drivetrain' => 'AWD',
        'top_speed' => '198 mph',
        'zero_to_sixty' => '3.7 sec',
        'features' => [
            'Luxury Rear Cabin',
            'Naim Audio System',
            'Adaptive Cruise Control',
            'Massaging Seats',
        ],
        'description' => "The Bentley Continental GT delivers a refined grand touring experience with rich materials and serious performance. It is elegant, powerful, and deeply comfortable.",
        'description_long' => "This coupe is ideal for drivers who want elite luxury and strong performance without sacrificing comfort or presence.",
        'images' => [
            'images/Bentley%20Continental%20GT.jpg',
        ],
    ],
    [
        'id' => 12,
        'name' => 'Mercedes-AMG G63',
        'tagline' => 'A bold luxury SUV with unmistakable presence and commanding capability.',
        'year' => '2025',
        'price' => '$175,000',
        'mileage' => '5,300 miles',
        'exterior_color' => 'Manufaktur Selenite Grey',
        'interior_color' => 'Black Nappa',
        'status' => 'In Stock',
        'engine' => '4.0L Twin-Turbo V8',
        'horsepower' => '577 hp',
        'torque' => '627 lb-ft',
        'transmission' => '9-Speed Automatic',
        'drivetrain' => 'AWD',
        'top_speed' => '149 mph',
        'zero_to_sixty' => '4.4 sec',
        'features' => [
            'AMG Performance Exhaust',
            'Panoramic Roof',
            'Burmester Sound System',
            'Off-Road Driving Modes',
        ],
        'description' => "The AMG G63 brings iconic design and serious performance to the luxury SUV segment. It is dramatic, powerful, and unmistakably bold.",
        'description_long' => "Inside, the cabin offers luxurious comfort and modern technology, making it a standout choice for drivers who want both style and capability.",
        'images' => [
            'images/Mercedes-AMG%20G63.jpg',
        ],
    ],
    [
        'id' => 13,
        'name' => 'Aston Martin DBX',
        'tagline' => 'A luxurious performance SUV with iconic British style.',
        'year' => '2025',
        'price' => '$190,000',
        'mileage' => '3,800 miles',
        'exterior_color' => 'Vulcan Blue',
        'interior_color' => 'Cinnamon Leather',
        'status' => 'In Stock',
        'engine' => '4.0L Twin-Turbo V8',
        'horsepower' => '542 hp',
        'torque' => '516 lb-ft',
        'transmission' => '9-Speed Automatic',
        'drivetrain' => 'AWD',
        'top_speed' => '181 mph',
        'zero_to_sixty' => '4.3 sec',
        'features' => [
            'Sport Suspension',
            'Premium Audio',
            'Panoramic Roof',
            'Massaging Seats',
        ],
        'description' => "The Aston Martin DBX combines elegance and performance in a crossover designed to turn heads. It is refined, athletic, and unmistakably premium.",
        'description_long' => "This SUV delivers a smooth, powerful ride alongside luxurious amenities that make every journey feel first-class.",
        'images' => [
            'images/aston-martin-dbx.jpg',
        ],
    ],
    [
        'id' => 14,
        'name' => 'Alfa Romeo Giulia Quadrifoglio',
        'tagline' => 'Italian passion and precision in a sharp performance sedan.',
        'year' => '2024',
        'price' => '$78,000',
        'mileage' => '6,100 miles',
        'exterior_color' => 'Rosso Competizione',
        'interior_color' => 'Black Leather',
        'status' => 'In Stock',
        'engine' => '2.9L Twin-Turbo V6',
        'horsepower' => '505 hp',
        'torque' => '443 lb-ft',
        'transmission' => '8-Speed Automatic',
        'drivetrain' => 'AWD',
        'top_speed' => '191 mph',
        'zero_to_sixty' => '3.8 sec',
        'features' => [
            'Adaptive Dampers',
            'Alcantara Interior',
            'Performance Steering Wheel',
            'Premium Sound System',
        ],
        'description' => "The Giulia Quadrifoglio is an Italian sport sedan with rich character and genuine athleticism. It stands out for its responsiveness and style.",
        'description_long' => "Its precision steering and muscular engine make it an exciting choice for drivers who want a more emotional performance car.",
        'images' => [
            'images/alfa-giulia-quadrifoglio.jpg',
        ],
    ],
    [
        'id' => 15,
        'name' => 'Porsche Cayenne Turbo E-Hybrid',
        'tagline' => 'A high-performance luxury SUV with electric efficiency and power.',
        'year' => '2025',
        'price' => '$145,000',
        'mileage' => '2,700 miles',
        'exterior_color' => 'Miami Blue',
        'interior_color' => 'Black/Beige',
        'status' => 'In Stock',
        'engine' => '4.0L V8 Plug-In Hybrid',
        'horsepower' => '729 hp',
        'torque' => '700 lb-ft',
        'transmission' => '8-Speed Automatic',
        'drivetrain' => 'AWD',
        'top_speed' => '183 mph',
        'zero_to_sixty' => '3.2 sec',
        'features' => [
            'Hybrid Performance',
            'Adaptive Air Suspension',
            'Premium Cabin Trim',
            'Panoramic Roof',
        ],
        'description' => "The Cayenne Turbo E-Hybrid combines Porsche prestige with electrified performance. It is powerful, efficient, and beautifully finished.",
        'description_long' => "This SUV delivers instant acceleration alongside daily comfort and cutting-edge hybrid technology.",
        'images' => [
            'images/porsche-cayenne-turbo-e-hybrid.jpg',
        ],
    ],
];
